site_name: pnp-zone documentation 
theme:
  name: material
repo_url: https://github.com/pnp-zone/pnp-zone
repo_name: pnp-zone/pnp-zone 
edit_uri: https://github.com/pnp-zone/docs/edit/main/docs/
markdown_extensions:
  - admonition
nav:
